// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.opentelemetry.io/otel/trace"
	"kratos-http-grpc/app/user/internal/conf"
	"kratos-http-grpc/app/user/internal/server"
	"kratos-http-grpc/app/user/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, data *conf.Data, traceTracerProvider trace.TracerProvider, logger log.Logger) (*kratos.App, func(), error) {
	userService := service.NewUserService(traceTracerProvider)
	httpServer := server.NewHTTPServer(confServer, traceTracerProvider, userService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
	}, nil
}
